# Generated by Django 3.2.7 on 2021-09-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='No more than 250 characters', max_length=250, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_published', models.DateTimeField(auto_now=True, verbose_name='Date published')),
                ('slug', models.SlugField(unique_for_date='date_published', verbose_name='Slag')),
                ('main_page', models.BooleanField(default=False, help_text='Show', verbose_name='Main')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ('-date_published',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='No more than 250 characters', max_length=250, verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'News catagory',
                'verbose_name_plural': 'News catagories',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Image')),
                ('title', models.CharField(blank=True, help_text='No more than 250 characters', max_length=250, verbose_name='Title')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Article image',
                'verbose_name_plural': 'Article images',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='blog.category', verbose_name='Categories'),
        ),
    ]
